# action.yml
name: 'Install'
description: 'Install project dependencies'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract versions from package.json
      id: extract-versions
      run: |
        node_version=$(jq -r '.engines.node' package.json)
        pnpm_version=$(jq -r '.packageManager' package.json | cut -d'@' -f2)
        echo "NODE_VERSION=$node_version" >> $GITHUB_ENV
        echo "PNPM_VERSION=$pnpm_version" >> $GITHUB_ENV
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Restore node_modules cache
      uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-node-modules-${{ hashFiles('pnpm-lock.yaml', '.npmrc', 'pnpm-workspace.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Install pnpm
      run: npm install -g pnpm@${{ env.PNPM_VERSION }}
      shell: bash

    - id: pnpm-cache
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV
      shell: bash

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install
      shell: bash
