name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 18
      PNPM_VERSION: 8

    steps:
      - uses: actions/checkout@v3

      - name: Setup pnpm and cache
        uses: ./.github/actions/prepare
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash

      - name: AI Code Reviewer
        uses: nextimecode/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
