name: preview

on:
  pull_request:
    branches: ['main']

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/prepare

      - name: Verify pnpm installation
        run: pnpm --version

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Verify pnpm
        run: pnpm --version

      - name: Run lint
        run: pnpm run lint

  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Verify pnpm
        run: pnpm --version

      - name: Run typecheck
        run: pnpm run typecheck

  audit:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Verify pnpm
        run: pnpm --version

      - name: Audit dependencies
        run: pnpm audit
