name: preview

on:
  pull_request:
    branches: ['main']

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: ./.github/actions/prepare

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: ./install

      - name: Run lint
        run: pnpm run lint

  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: ./install

      - name: Run typecheck
        run: pnpm run typecheck

  audit:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: ./install

      - name: Audit dependencies
        run: pnpm audit
