name: preview

on:
  pull_request:
    branches: ['main']

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node_version: ${{ steps.extract-versions.outputs.node_version }}
      pnpm_version: ${{ steps.extract-versions.outputs.pnpm_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract versions from package.json
        id: extract-versions
        run: |
          echo "node_version=$(jq -r '.engines.node' package.json)" >> $GITHUB_OUTPUT
          echo "pnpm_version=$(jq -r '.packageManager' package.json | cut -d'@' -f2)" >> $GITHUB_OUTPUT
        shell: bash

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node_version }}

      - name: Install pnpm
        run: npm install -g pnpm@${{ needs.setup.outputs.pnpm_version }}
        shell: bash

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node_version }}

      - name: Install pnpm
        run: npm install -g pnpm@${{ needs.setup.outputs.pnpm_version }}
        shell: bash

      - name: Install dependencies
        run: pnpm install

      - name: Run typecheck
        run: pnpm run typecheck

  audit:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.setup.outputs.node_version }}

      - name: Install pnpm
        run: npm install -g pnpm@${{ needs.setup.outputs.pnpm_version }}
        shell: bash

      - name: Install dependencies
        run: pnpm install

      - name: Audit dependencies
        run: pnpm audit
