name: preview

on:
  pull_request:
    branches: ['main']

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node_version: ${{ steps.extract-versions.outputs.node_version }}
      pnpm_version: ${{ steps.extract-versions.outputs.pnpm_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Extract versions from package.json
        id: extract-versions
        run: |
          node_version=$(jq -r '.engines.node' package.json)
          pnpm_version=$(jq -r '.packageManager' package.json | cut -d'@' -f2)
          echo "::set-output name=node_version::$node_version"
          echo "::set-output name=pnpm_version::$pnpm_version"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.extract-versions.outputs.node_version }}

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.setup.outputs.node_version }}

      - name: Install pnpm
        run: npm install -g pnpm@${{ needs.setup.outputs.pnpm_version }}

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.setup.outputs.node_version }}

      - name: Install pnpm
        run: npm install -g pnpm@${{ needs.setup.outputs.pnpm_version }}

      - name: Install dependencies
        run: pnpm install

      - name: Run typecheck
        run: pnpm run typecheck

  audit:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.setup.outputs.node_version }}

      - name: Install pnpm
        run: npm install -g pnpm@${{ needs.setup.outputs.pnpm_version }}

      - name: Install dependencies
        run: pnpm install

      - name: Audit dependencies
        run: pnpm audit
