name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write # Permissões de escrita para publicação de releases no GitHub
  issues: write # Permissão para comentar issues relacionadas
  pull-requests: write # Permissão para comentar PRs relacionadas
  id-token: write # Permissão para OIDC com npm

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Faz o checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Configura Node.js e pnpm (action composta)
      - name: Setup Node.js and pnpm
        uses: ./.github/actions/prepare

      # Publica a versão no NPM usando changesets
      - name: Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release # Comando que dispara a publicação
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Cria a release no GitHub
      - name: Create GitHub Release
        if: steps.changesets.outputs.published == 'true'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            🚀 Novo release publicado!
            - Verifique as alterações no changelog.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
